<?php

namespace App\Filament\Resources;

use App\Filament\Resources\GameExclusiveResource\Pages;
use App\Filament\Resources\GameExclusiveResource\RelationManagers;
use App\Models\Category;
use App\Models\GameExclusive;
use Filament\Forms;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class GameExclusiveResource extends Resource
{
    protected static ?string $model = GameExclusive::class;

    protected static ?string $navigationIcon = 'heroicon-o-puzzle-piece';

    protected static ?string $navigationLabel = 'Jogos Plataforma';

    protected static ?string $modelLabel = 'Jogos Plataforma';

    protected static ?string $navigationGroup = 'Meus Jogos';

    protected static ?string $slug = 'meus-jogos-exclusivos';

    protected static ?string $recordTitleAttribute = 'name';

    protected static ?int $navigationSort = -1;

    /**
     * @return string|null
     */
    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|array|null
     */
    public static function getNavigationBadgeColor(): string|array|null
    {
        return static::getModel()::count() > 5 ? 'success' : 'warning'; // TODO: Change the autogenerated stub
    }


    /**
     * @param Form $form
     * @return Form
     */
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Games')
                    ->description('Cadastrando um jogo')
                    ->schema([
                        Forms\Components\Select::make('category_id')
                            ->label('Categoria')
                            ->placeholder('Selecione uma categoria')
                            ->relationship(name: 'category', titleAttribute: 'name')
                            ->options(
                                fn($get) => Category::query()
                                    ->pluck('name', 'id')
                            )
                            ->searchable()
                            ->preload()
                            ->live()
                            ->columnSpanFull(),

                        Forms\Components\Group::make()
                            ->schema([
                                Forms\Components\TextInput::make('name')
                                    ->label('Nome do jogo')
                                    ->placeholder('Digite o nome do jogo')
                                    ->required()
                                    ->maxLength(191),
                                Forms\Components\TextInput::make('uuid')
                                    ->label('UUID')
                                    ->placeholder('Digite o UUID do jogo, a pasta onde o jogo está')
                                    ->required()
                                    ->maxLength(191),
                            ])->columns(2),

                        RichEditor::make('description')
                            ->columnSpanFull(),
                        Forms\Components\Group::make()
                            ->schema([
                                Forms\Components\FileUpload::make('cover')
                                    ->label('Capa')
                                    ->placeholder('Carregue a capa do jogo')
                                    ->image()
                                    ->required(),
                                Forms\Components\FileUpload::make('icon')
                                    ->label('Icone')
                                    ->placeholder('Carregue a icone do jogo')
                                    ->image()
                                    ->required(),
                            ])->columns(2),
                        Forms\Components\Group::make()
                            ->schema([
                                Forms\Components\TextInput::make('winLength')
                                    ->required()
                                    ->numeric()
                                    ->default(3),
                                Forms\Components\TextInput::make('loseLength')
                                    ->required()
                                    ->numeric()
                                    ->default(20),
                                Forms\Components\TextInput::make('influencer_winLength')
                                    ->required()
                                    ->numeric()
                                    ->default(20),
                                Forms\Components\TextInput::make('influencer_loseLength')
                                    ->required()
                                    ->numeric()
                                    ->default(1),
                            ])->columns(4),
                        Forms\Components\Toggle::make('active')
                            ->label('Ativar Jogo')
                            ->default(true)
                            ->required()
                            ->columnSpanFull(),
                    ])
            ]);
    }

    /**
     * @param Table $table
     * @return Table
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('category.name')
                    ->label('Categoria')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('name')
                    ->label('Nome')
                    ->searchable(),

                Tables\Columns\ImageColumn::make('cover')
                    ->label('Capa'),
                Tables\Columns\ImageColumn::make('icon')
                    ->label('Icone'),

                Tables\Columns\TextColumn::make('winLength')
                    //->toggleable(isToggledHiddenByDefault: true)
                        ->label('Vitoria')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('loseLength')
                    //->toggleable(isToggledHiddenByDefault: true)
                    ->label('Perda')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('influencer_winLength')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('influencer_loseLength')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->numeric()
                    ->sortable(),
                Tables\Columns\ToggleColumn::make('active')
                    ->label('Ativo'),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Data')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions(env('APP_DEMO') ? [] :[
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGameExclusives::route('/'),
            'create' => Pages\CreateGameExclusive::route('/create'),
            'edit' => Pages\EditGameExclusive::route('/{record}/edit'),
        ];
    }
}
