<?php

namespace App\Filament\Resources;

use App\Filament\Resources\VibraCasinoGameResource\Pages;
use App\Filament\Resources\VibraCasinoGameResource\RelationManagers;
use App\Models\VibraCasinoGame;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class VibraCasinoGameResource extends Resource
{
    protected static ?string $model = VibraCasinoGame::class;

    protected static ?string $navigationIcon = 'heroicon-o-puzzle-piece';

    protected static ?string $navigationLabel = 'Jogos Vibra';

    protected static ?string $modelLabel = 'Jogos Vibra';

    /**
     * @return string|null
     */
    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|array|null
     */
    public static function getNavigationBadgeColor(): string|array|null
    {
        return static::getModel()::count() > 5 ? 'success' : 'warning'; // TODO: Change the autogenerated stub
    }

    /**
     * @param Form $form
     * @return Form
     */
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Vibra Jogos')
                    ->schema([
                        Forms\Components\TextInput::make('game_name')
                            ->label('Nome do Jogo')
                            ->placeholder('Digite o nome do jogo')
                            ->maxLength(50),
                        Forms\Components\TextInput::make('game_id')
                            ->label('Game Id')
                            ->placeholder('Digite o jogo id')
                            ->maxLength(50),
                        Forms\Components\FileUpload::make('game_cover')
                            ->label('Imagem')
                            ->placeholder('Carregue a imagem do jogo')
                            ->image()
                            ->columnSpanFull()
                            ->required(),
                        Forms\Components\Toggle::make('status')
                            ->columnSpanFull()
                            ->default(true)
                            ->required(),
                    ])->columns(2),
            ]);
    }

    /**
     * @param Table $table
     * @return Table
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\ImageColumn::make('game_cover'),
                Tables\Columns\TextColumn::make('game_name')
                    ->label('Nome')
                    ->searchable(),
                Tables\Columns\TextColumn::make('game_id')
                    ->label('Game ID')
                    ->searchable(),
                Tables\Columns\ToggleColumn::make('status')
                    ->label('Status'),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListVibraCasinoGames::route('/'),
            'create' => Pages\CreateVibraCasinoGame::route('/create'),
            'edit' => Pages\EditVibraCasinoGame::route('/{record}/edit'),
        ];
    }
}
